import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Discussion from "../components/Discussion";
import Footer from "../components/Footer";
import Gallery from "../components/Gallery";
import Header from "../components/Header";
import Location from "../components/Location";
import Welcome from "../components/Welcome";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mundhra Garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <Header />
        <Welcome />
        <Gallery />
        <About />
        <Location />
        <Contact />
        <Discussion />
        <Footer />
      </main>
    </>
  );
}
